### ISSUE TITLE
在Android14下的HyperOS中背景功能无效

### ISSUE THREAD

**Issue by jyfyge** [Xposed-Modules-Repo/com.gswxxn.restoresplashscreen#3]
不知道这个应该提供哪里的日志，lsp日志中似乎没有看到相关内容？

**Comment by GSWXXN** [comment]
请先尝试使用模块 CI 版，CI版修复了部分在Android14上可能遇到的问题。

**Comment by jyfyge** [comment]
[LSPosed_2023-12-02T19_45_07.369702.zip](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/files/13536154/LSPosed_2023-12-02T19_45_07.369702.zip)

更新最新CI版本后出现系统界面多次崩溃，关闭模块后暂时没有复现，怀疑是此模块的问题，大佬能看下log吗

**Comment by GSWXXN** [comment]
看起来遮罩模块运行是正常的，导致系统界面崩溃是由于某个模块对锁屏界面状态栏的操作出现了异常，但是看不出来具体是哪个模块导致的

看到你好像安装了很多多功能的“大杂烩”模块，建议先把它们禁用试试，如果不会出现问题了，再逐个排查

**Comment by jyfyge** [comment]
咦，那就很奇怪了，因为这些模块我并没有设置过修改锁屏状态栏，对锁屏的修改只有 充电时显示电压电流、“角落按钮添加模糊 左下按钮长按切换手电筒状态”。从昨天晚上到今天早上没有开启遮罩模块期间，系统界面没有发生过崩溃，今天早上开始遮罩模块后又发生过两次崩溃，禁用遮罩模块后重新再打开，目前还没有崩溃过。观察下来，似乎发生崩溃的主要场景在后台多任务界面点击应用图标查看应用详情的时候较易卡死崩溃

**Comment by GSWXXN** [comment]
从日志中可以看出来导致系统界面崩溃的原因是某个模块 反射查找`com.android.systemui.statusbar.KeyguardIndicationController` 类时出错

在日志中可以看有以下的模块对你的系统界面进行了 Hook   *(点击可以跳转到对应仓库)*

* [MIUI Extra](https://github.com/Art-Chen/MIUI-Extra-YukiAPI)
* [customiuizer](https://github.com/MonwF/customiuizer)
* [HyperCeiler](https://github.com/ReChronoRain/HyperCeiler)
* [StarVoyager](https://github.com/hosizoraru/StarVoyager)
* [RestoreSplashScreen](https://github.com/GSWXXN/RestoreSplashScreen)
  
好在以上模块都是开源的, 通过搜索发现下面两个模块对这个类进行了操作 *(点击可以跳转到对应相关实现的源码位置)*

* [HyperCeiler](https://github.com/ReChronoRain/HyperCeiler/blob/cc4f7e8f999d1cefa6600f0420da111d5d902bee/app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/lockscreen/ChargingCVP.kt#L37-L60)
* [StarVoyager](https://github.com/hosizoraru/StarVoyager/blob/56d7760733bd17ddb6fe99995a20de57ac027410/app/src/main/kotlin/star/sky/voyager/hook/hooks/systemui/LockscreenChargingInfo.kt#L36-L37)

对应的功能:
* StarVoyager: 显示充电功率
* HyperCeiler: 锁屏底部显示充电信息

根据堆栈信息和二者的代码实现, 我更倾向于是 HyperCeiler 的 “锁屏底部显示充电信息” 出现了异常 ~(只是不负责任的推测, 如果是错的, 绀漓看到了别打我)~

以上只是简单的查找分析, 你可以试试关闭这些功能, 再看看是否还有崩溃


除了查找`com.android.systemui.statusbar.KeyguardIndicationController`类时的错误, 我在日志里没有再看到系统界面崩溃的其他异常信息了

**Comment by GSWXXN** [comment]
根据你的描述, 崩溃是偶发性的? 那没有崩溃的时候 CI 版启动遮罩的背景功能还是失效的吗?

**Comment by jyfyge** [comment]
确实是偶发性的。没有崩溃的时候背景功能正常生效了。我现在已经关了HyperCeiler的锁屏底部充电信息了，我再观察一下会不会崩溃。不过这个功能从我升到HyperOS就在用，前几天的时候倒也没崩过。

**Comment by jyfyge** [comment]
经过一周的试用之后，关闭HyperCeiler的锁屏充电信息后，系统界面的确不再崩溃。但是还是感觉遮罩模块、HyperCeiler可能都有问题。因为关闭遮罩模块使用HyperCeiler的锁屏充电信息，系统界面似乎是不会崩溃的。而我最近更换使用了YukiVoyager模块里的锁屏充电功率显示，目前和遮罩模块一起使用，还没有发生过系统界面崩溃

**Comment by GSWXXN** [comment]
确实 还有人反馈过相同的问题，但这个问题只会出现在安卓14上，日志又看不出来更多的信息了，也就只能等到我的设备可以升级到HyperOS 之后再尝试复现解决了
