### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by naniccc** [Xposed-Modules-Repo/com.gswxxn.restoresplashscreen#4]
设备：ColorOS14 Android14
①有的app开屏自定义图标没替换成功，例如：京东、小米运动健康
②手机深色模式下，莫奈取色的背景比别的app浅很多
![Screenshot_2024-01-03-00-47-01-61_4fbb30eb7b7166119bd25e41eddeee2f](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/assets/57870281/3b1bc5f4-30bf-4c7e-bc73-2aa734d65c2c)
![Screenshot_2024-01-03-00-47-19-71_dfbfc8a7bdd47ae3d9fa4dbf55e6dd19](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/assets/57870281/5c233351-3a3f-43bf-adc6-7c0b3671c933)
![IMG_20240103_011209](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/assets/57870281/af8aca20-2c8c-4df8-9c5a-a3d05486bf50)

**Comment by GSWXXN** [comment]
京东 小米健康 这两个应用主动适配了 Splash Screen 特性, 模块默认不对适配 Splash Screen 的应用进行操作, 如果你不喜欢可以在 图标 - 忽略应用主动设置的图标中添加这些应用

关于取色, 这是个个人喜好的问题, 我会尝试对比一下不同的取色方案的

**Comment by naniccc** [comment]
> 京东 小米健康 这两个应用主动适配了 Splash Screen 特性, 模块默认不对适配 Splash Screen 的应用进行操作, 如果你不喜欢可以在 图标 - 忽略应用主动设置的图标中添加这些应用
> 
> 关于取色, 这是个个人喜好的问题, 我会尝试对比一下不同的取色方案的

①已经忽略了，但是椒盐音乐能生效，京东、小米健康不生效
②好像深色莫奈取色都是统一的，别的app会深一点，或者再加个选项呢，比如“暗暗色”
![Stitch_20240103_034438](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/assets/57870281/3987f35e-0b69-48b9-9e78-7bea11db3210)
![Stitch_20240103_034159](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/assets/57870281/ec49a257-f6e5-4f74-bfa6-cb48bf96bcfe)

**Comment by GSWXXN** [comment]
我测试下来把 京东、小米健康 加到 ”忽略应用主动设置的图标“ 列表中是可以生效的, 你可能需要再次打开京东、小米健康才能看到效果?
另外你可以把你的壁纸发给我一下吗, 我测试几个壁纸这些应用内的背景都是纯黑色, 如果大部分取得的背景色都是黑色, 那这个功能是不是也就没有意义了呢

**Comment by naniccc** [comment]
> 我测试下来把 京东、小米健康 加到 ”忽略应用主动设置的图标“ 列表中是可以生效的, 你可能需要再次打开京东、小米健康才能看到效果? 另外你可以把你的壁纸发给我一下吗, 我测试几个壁纸这些应用内的背景都是纯黑色, 如果大部分取得的背景色都是黑色, 那这个功能是不是也就没有意义了呢

如图是这样设置的吧？重启了，还是没有生效，但椒盐音乐生效

![Stitch_20240103_041923](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/assets/57870281/76ba46a6-138b-423c-9818-8af09d4618bf)
![821951917b610af39b4fe0124dd21f42](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/assets/57870281/4b32fd58-3a55-41ef-89c2-343ff211f602)

**Comment by GSWXXN** [comment]
已经修改了深色模式下莫奈取色方案, 你可以下载最新 CI 版本测试一下, 后续我可能会出类似”高级设置“的项目, 来精细调整一些参数, 比如图标缩小比例, 圆角大小等, 也会包括这个取色方案的选择

关于图标问题: 你可以给我发一下详细日志吗, 先在模块基础设置中打开启用日志, 然后冷启动几次京东或小米运动健康, 再从Lsp管理器中导出日志

**Comment by GSWXXN** [comment]
你现在的设置应该是没问题的

**Comment by naniccc** [comment]
> 已经修改了深色模式下莫奈取色方案, 你可以下载最新 CI 版本测试一下, 后续我可能会出类似”高级设置“的项目, 来精细调整一些参数, 比如图标缩小比例, 圆角大小等, 也会包括这个取色方案的选择
> 
> 关于图标问题: 你可以给我发一下详细日志吗, 先在模块基础设置中打开启用日志, 然后冷启动几次京东或小米运动健康, 再从Lsp管理器中导出日志

是这样吗？

[LSPosed_2024-01-04T00_01_07.482511.zip](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/files/13821108/LSPosed_2024-01-04T00_01_07.482511.zip)

**Comment by GSWXXN** [comment]
看起来相关流程确实没有被执行，可以再麻烦提取一下你的系统界面嘛，我需要详细分析一下

**Comment by naniccc** [comment]
> 看起来相关流程确实没有被执行，可以再麻烦提取一下你的系统界面嘛，我需要详细分析一下

应该怎么操作？
![Screenshot_2024-01-04-00-27-18-25_084ab3bc34f7aa7ccff83653f52abafc](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/assets/57870281/41f53ceb-e77b-48e6-aa52-4e2044f8486e)

**Comment by GSWXXN** [comment]
在 MT管理器里选左上角三个杠打开侧边栏 - 安装包提取 - 系统应用 - 搜索 系统界面 - 点击提取安装包 - 定位

然后把这个安装包随便丢到一个网盘里发给我就行

**Comment by naniccc** [comment]
> 在 MT管理器里选左上角三个杠打开侧边栏 - 安装包提取 - 系统应用 - 搜索 系统界面 - 点击提取安装包 - 定位
> 
> 然后把这个安装包随便丢到一个网盘里发给我就行

https://www.123pan.com/s/gKKjVv-dDOCh.html

**Comment by GSWXXN** [comment]
尝试修了一下，你可以下载最新 CI 版测试

**Comment by naniccc** [comment]
> 尝试修了一下，你可以下载最新 CI 版测试
已安装，这回正常了
